import { describe, expect, it } from 'bun:test';
import { calculateEwtEintraege } from '@/features/EWT/utils';
import type { IVorgabenU } from '@/core/types/IVorgabenU';
import { VorgabenUMock } from './mockData';
import type { IMonatsDaten } from '@/core/types';

describe('berechnen', () => {
  it('sollte die richtigen Daten für einen gegebenen Monat berechnen', () => {
    const vorgabenU: IVorgabenU = VorgabenUMock;

    const daten: IMonatsDaten['EWT'] = [
      {
        Tag: '2023-04-03',
        Einsatzort: 'Kirchheim',
        Schicht: 'T',
        abWE: '',
        ab1E: '',
        anEE: '',
        beginE: '',
        endeE: '',
        abEE: '',
        an1E: '',
        anWE: '',
        berechnen: true,
      },
      {
        Tag: '2023-04-04',
        Einsatzort: 'Hattenbach',
        Schicht: 'T',
        abWE: '',
        ab1E: '',
        anEE: '',
        beginE: '',
        endeE: '',
        abEE: '',
        an1E: '',
        anWE: '',
        berechnen: true,
      },
      {
        Tag: '2023-04-05',
        Einsatzort: 'Richthof',
        Schicht: 'T',
        abWE: '',
        ab1E: '',
        anEE: '',
        beginE: '',
        endeE: '',
        abEE: '',
        an1E: '',
        anWE: '',
        berechnen: true,
      },
      {
        Tag: '2023-04-06',
        Einsatzort: 'Langenschwarz',
        Schicht: 'T',
        abWE: '',
        ab1E: '',
        anEE: '',
        beginE: '',
        endeE: '',
        abEE: '',
        an1E: '',
        anWE: '',
        berechnen: true,
      },
      {
        Tag: '2023-04-07',
        Einsatzort: 'Wildsberg',
        Schicht: 'T',
        abWE: '',
        ab1E: '',
        anEE: '',
        beginE: '',
        endeE: '',
        abEE: '',
        an1E: '',
        anWE: '',
        berechnen: true,
      },
      {
        Tag: '2023-04-08',
        Einsatzort: 'Licherode',
        Schicht: 'T',
        abWE: '',
        ab1E: '',
        anEE: '',
        beginE: '',
        endeE: '',
        abEE: '',
        an1E: '',
        anWE: '',
        berechnen: true,
      },
      {
        Tag: '2023-04-15',
        Einsatzort: 'Licherode',
        Schicht: 'N',
        abWE: '',
        ab1E: '',
        anEE: '',
        beginE: '',
        endeE: '',
        abEE: '',
        an1E: '',
        anWE: '',
        berechnen: true,
      },
      {
        Tag: '2023-04-16',
        Einsatzort: 'Ersrode',
        Schicht: 'N',
        abWE: '',
        ab1E: '',
        anEE: '',
        beginE: '',
        endeE: '',
        abEE: '',
        an1E: '',
        anWE: '',
        berechnen: true,
      },
      {
        Tag: '2023-04-17',
        Einsatzort: 'Mühlbach',
        Schicht: 'N',
        abWE: '',
        ab1E: '',
        anEE: '',
        beginE: '',
        endeE: '',
        abEE: '',
        an1E: '',
        anWE: '',
        berechnen: true,
      },
      {
        Tag: '2023-04-18',
        Einsatzort: 'Kirchheim',
        Schicht: 'N',
        abWE: '',
        ab1E: '',
        anEE: '',
        beginE: '',
        endeE: '',
        abEE: '',
        an1E: '',
        anWE: '',
        berechnen: true,
      },
      {
        Tag: '2023-04-22',
        Einsatzort: 'Hattenbach',
        Schicht: 'N',
        abWE: '',
        ab1E: '',
        anEE: '',
        beginE: '',
        endeE: '',
        abEE: '',
        an1E: '',
        anWE: '',
        berechnen: true,
      },
      {
        Tag: '2023-04-23',
        Einsatzort: 'Richthof',
        Schicht: 'N',
        abWE: '',
        ab1E: '',
        anEE: '',
        beginE: '',
        endeE: '',
        abEE: '',
        an1E: '',
        anWE: '',
        berechnen: true,
      },
      {
        Tag: '2023-04-24',
        Einsatzort: 'Langenschwarz',
        Schicht: 'N',
        abWE: '',
        ab1E: '',
        anEE: '',
        beginE: '',
        endeE: '',
        abEE: '',
        an1E: '',
        anWE: '',
        berechnen: true,
      },
      {
        Tag: '2023-04-25',
        Einsatzort: 'Michelsrombach',
        Schicht: 'N',
        abWE: '',
        ab1E: '',
        anEE: '',
        beginE: '',
        endeE: '',
        abEE: '',
        an1E: '',
        anWE: '',
        berechnen: true,
      },
    ];

    // Erwartete Ergebnisse
    const expected: IMonatsDaten['EWT'] = [
      {
        Tag: '2023-04-03',
        Buchungstag: '2023-04-03',
        Einsatzort: 'Kirchheim',
        Schicht: 'T',
        abWE: '06:40',
        ab1E: '07:20',
        anEE: '07:30',
        beginE: '07:00',
        endeE: '15:45',
        abEE: '15:15',
        an1E: '15:25',
        anWE: '16:05',
        berechnen: true,
      },
      {
        Tag: '2023-04-04',
        Buchungstag: '2023-04-04',
        Einsatzort: 'Hattenbach',
        Schicht: 'T',
        abWE: '06:40',
        ab1E: '07:20',
        anEE: '07:35',
        beginE: '07:00',
        endeE: '15:45',
        abEE: '15:10',
        an1E: '15:25',
        anWE: '16:05',
        berechnen: true,
      },
      {
        Tag: '2023-04-05',
        Buchungstag: '2023-04-05',
        Einsatzort: 'Richthof',
        Schicht: 'T',
        abWE: '06:40',
        ab1E: '07:20',
        anEE: '07:40',
        beginE: '07:00',
        endeE: '15:45',
        abEE: '15:05',
        an1E: '15:25',
        anWE: '16:05',
        berechnen: true,
      },
      {
        Tag: '2023-04-06',
        Buchungstag: '2023-04-06',
        Einsatzort: 'Langenschwarz',
        Schicht: 'T',
        abWE: '06:40',
        ab1E: '07:20',
        anEE: '07:55',
        beginE: '07:00',
        endeE: '15:45',
        abEE: '14:50',
        an1E: '15:25',
        anWE: '16:05',
        berechnen: true,
      },
      {
        Tag: '2023-04-07',
        Buchungstag: '2023-04-07',
        Einsatzort: 'Wildsberg',
        Schicht: 'T',
        abWE: '06:40',
        ab1E: '07:20',
        anEE: '08:00',
        beginE: '07:00',
        endeE: '13:00',
        abEE: '12:00',
        an1E: '12:40',
        anWE: '13:20',
        berechnen: true,
      },
      {
        Tag: '2023-04-08',
        Buchungstag: '2023-04-08',
        Einsatzort: 'Licherode',
        Schicht: 'T',
        abWE: '06:40',
        ab1E: '07:20',
        anEE: '07:55',
        beginE: '07:00',
        endeE: '15:45',
        abEE: '14:50',
        an1E: '15:25',
        anWE: '16:05',
        berechnen: true,
      },
      {
        Tag: '2023-04-15',
        Buchungstag: '2023-04-16',
        Einsatzort: 'Licherode',
        Schicht: 'N',
        abWE: '19:25',
        ab1E: '20:30',
        anEE: '21:05',
        beginE: '19:45',
        endeE: '06:15',
        abEE: '04:55',
        an1E: '05:30',
        anWE: '06:35',
        berechnen: true,
      },
      {
        Tag: '2023-04-16',
        Buchungstag: '2023-04-17',
        Einsatzort: 'Ersrode',
        Schicht: 'N',
        abWE: '19:25',
        ab1E: '20:30',
        anEE: '20:55',
        beginE: '19:45',
        endeE: '06:15',
        abEE: '05:05',
        an1E: '05:30',
        anWE: '06:35',
        berechnen: true,
      },
      {
        Tag: '2023-04-17',
        Buchungstag: '2023-04-18',
        Einsatzort: 'Mühlbach',
        Schicht: 'N',
        abWE: '19:25',
        ab1E: '20:30',
        anEE: '20:50',
        beginE: '19:45',
        endeE: '06:15',
        abEE: '05:10',
        an1E: '05:30',
        anWE: '06:35',
        berechnen: true,
      },
      {
        Tag: '2023-04-18',
        Buchungstag: '2023-04-19',
        Einsatzort: 'Kirchheim',
        Schicht: 'N',
        abWE: '19:25',
        ab1E: '20:30',
        anEE: '20:40',
        beginE: '19:45',
        endeE: '06:15',
        abEE: '05:20',
        an1E: '05:30',
        anWE: '06:35',
        berechnen: true,
      },
      {
        Tag: '2023-04-22',
        Buchungstag: '2023-04-23',
        Einsatzort: 'Hattenbach',
        Schicht: 'N',
        abWE: '19:25',
        ab1E: '20:30',
        anEE: '20:45',
        beginE: '19:45',
        endeE: '06:15',
        abEE: '05:15',
        an1E: '05:30',
        anWE: '06:35',
        berechnen: true,
      },
      {
        Tag: '2023-04-23',
        Buchungstag: '2023-04-24',
        Einsatzort: 'Richthof',
        Schicht: 'N',
        abWE: '19:25',
        ab1E: '20:30',
        anEE: '20:50',
        beginE: '19:45',
        endeE: '06:15',
        abEE: '05:10',
        an1E: '05:30',
        anWE: '06:35',
        berechnen: true,
      },
      {
        Tag: '2023-04-24',
        Buchungstag: '2023-04-25',
        Einsatzort: 'Langenschwarz',
        Schicht: 'N',
        abWE: '19:25',
        ab1E: '20:30',
        anEE: '21:05',
        beginE: '19:45',
        endeE: '06:15',
        abEE: '04:55',
        an1E: '05:30',
        anWE: '06:35',
        berechnen: true,
      },
      {
        Tag: '2023-04-25',
        Buchungstag: '2023-04-26',
        Einsatzort: 'Michelsrombach',
        Schicht: 'N',
        abWE: '19:25',
        ab1E: '20:30',
        anEE: '21:10',
        beginE: '19:45',
        endeE: '06:15',
        abEE: '04:50',
        an1E: '05:30',
        anWE: '06:35',
        berechnen: true,
      },
    ];

    // Führen Sie die berechnen-Funktion aus
    const result = calculateEwtEintraege(vorgabenU, daten);

    // Überprüfen Sie die Ergebnisse
    expect(result).toEqual(expected);
  });
});
