import { describe, expect, it } from "vitest";
import { berechnen } from "../src/ts/EWT/utils";
import { IDaten } from "../src/ts/interfaces/IDaten";
import { IVorgabenU } from "../src/ts/interfaces/IVorgabenU";
import { VorgabenUMock } from "./mockData";

describe("berechnen", () => {
	it("sollte die richtigen Daten für einen gegebenen Monat berechnen", () => {
		const vorgabenU: IVorgabenU = VorgabenUMock;

		const daten: IDaten["EWT"] = [
			{
				tagE: "03",
				eOrtE: "Kirchheim",
				schichtE: "T",
				abWE: "",
				ab1E: "",
				anEE: "",
				beginE: "",
				endeE: "",
				abEE: "",
				an1E: "",
				anWE: "",
				berechnen: true,
			},
			{
				tagE: "04",
				eOrtE: "Hattenbach",
				schichtE: "T",
				abWE: "",
				ab1E: "",
				anEE: "",
				beginE: "",
				endeE: "",
				abEE: "",
				an1E: "",
				anWE: "",
				berechnen: true,
			},
			{
				tagE: "05",
				eOrtE: "Richthof",
				schichtE: "T",
				abWE: "",
				ab1E: "",
				anEE: "",
				beginE: "",
				endeE: "",
				abEE: "",
				an1E: "",
				anWE: "",
				berechnen: true,
			},
			{
				tagE: "06",
				eOrtE: "Langenschwarz",
				schichtE: "T",
				abWE: "",
				ab1E: "",
				anEE: "",
				beginE: "",
				endeE: "",
				abEE: "",
				an1E: "",
				anWE: "",
				berechnen: true,
			},
			{
				tagE: "07",
				eOrtE: "Wildsberg",
				schichtE: "T",
				abWE: "",
				ab1E: "",
				anEE: "",
				beginE: "",
				endeE: "",
				abEE: "",
				an1E: "",
				anWE: "",
				berechnen: true,
			},
			{
				tagE: "08",
				eOrtE: "Licherode",
				schichtE: "T",
				abWE: "",
				ab1E: "",
				anEE: "",
				beginE: "",
				endeE: "",
				abEE: "",
				an1E: "",
				anWE: "",
				berechnen: true,
			},
			{
				tagE: "15",
				eOrtE: "Licherode",
				schichtE: "N",
				abWE: "",
				ab1E: "",
				anEE: "",
				beginE: "",
				endeE: "",
				abEE: "",
				an1E: "",
				anWE: "",
				berechnen: true,
			},
			{
				tagE: "16",
				eOrtE: "Ersrode",
				schichtE: "N",
				abWE: "",
				ab1E: "",
				anEE: "",
				beginE: "",
				endeE: "",
				abEE: "",
				an1E: "",
				anWE: "",
				berechnen: true,
			},
			{
				tagE: "17",
				eOrtE: "Mühlbach",
				schichtE: "N",
				abWE: "",
				ab1E: "",
				anEE: "",
				beginE: "",
				endeE: "",
				abEE: "",
				an1E: "",
				anWE: "",
				berechnen: true,
			},
			{
				tagE: "18",
				eOrtE: "Kirchheim",
				schichtE: "N",
				abWE: "",
				ab1E: "",
				anEE: "",
				beginE: "",
				endeE: "",
				abEE: "",
				an1E: "",
				anWE: "",
				berechnen: true,
			},
			{
				tagE: "22",
				eOrtE: "Hattenbach",
				schichtE: "BN",
				abWE: "",
				ab1E: "",
				anEE: "",
				beginE: "",
				endeE: "",
				abEE: "",
				an1E: "",
				anWE: "",
				berechnen: true,
			},
			{
				tagE: "23",
				eOrtE: "Richthof",
				schichtE: "BN",
				abWE: "",
				ab1E: "",
				anEE: "",
				beginE: "",
				endeE: "",
				abEE: "",
				an1E: "",
				anWE: "",
				berechnen: true,
			},
			{
				tagE: "24",
				eOrtE: "Langenschwarz",
				schichtE: "BN",
				abWE: "",
				ab1E: "",
				anEE: "",
				beginE: "",
				endeE: "",
				abEE: "",
				an1E: "",
				anWE: "",
				berechnen: true,
			},
			{
				tagE: "25",
				eOrtE: "Michelsrombach",
				schichtE: "BN",
				abWE: "",
				ab1E: "",
				anEE: "",
				beginE: "",
				endeE: "",
				abEE: "",
				an1E: "",
				anWE: "",
				berechnen: true,
			},
		];

		const jahr = 2023;
		const monat = 4;

		// Erwartete Ergebnisse
		const expected: IDaten["EWT"] = [
			{
				tagE: "03",
				eOrtE: "Kirchheim",
				schichtE: "T",
				abWE: "06:40",
				ab1E: "07:20",
				anEE: "07:30",
				beginE: "07:00",
				endeE: "15:45",
				abEE: "15:15",
				an1E: "15:25",
				anWE: "16:05",
				berechnen: true,
			},
			{
				tagE: "04",
				eOrtE: "Hattenbach",
				schichtE: "T",
				abWE: "06:40",
				ab1E: "07:20",
				anEE: "07:35",
				beginE: "07:00",
				endeE: "15:45",
				abEE: "15:10",
				an1E: "15:25",
				anWE: "16:05",
				berechnen: true,
			},
			{
				tagE: "05",
				eOrtE: "Richthof",
				schichtE: "T",
				abWE: "06:40",
				ab1E: "07:20",
				anEE: "07:40",
				beginE: "07:00",
				endeE: "15:45",
				abEE: "15:05",
				an1E: "15:25",
				anWE: "16:05",
				berechnen: true,
			},
			{
				tagE: "06",
				eOrtE: "Langenschwarz",
				schichtE: "T",
				abWE: "06:40",
				ab1E: "07:20",
				anEE: "07:55",
				beginE: "07:00",
				endeE: "15:45",
				abEE: "14:50",
				an1E: "15:25",
				anWE: "16:05",
				berechnen: true,
			},
			{
				tagE: "07",
				eOrtE: "Wildsberg",
				schichtE: "T",
				abWE: "06:40",
				ab1E: "07:20",
				anEE: "08:00",
				beginE: "07:00",
				endeE: "13:00",
				abEE: "12:00",
				an1E: "12:40",
				anWE: "13:20",
				berechnen: true,
			},
			{
				tagE: "08",
				eOrtE: "Licherode",
				schichtE: "T",
				abWE: "06:40",
				ab1E: "07:20",
				anEE: "07:55",
				beginE: "07:00",
				endeE: "15:45",
				abEE: "14:50",
				an1E: "15:25",
				anWE: "16:05",
				berechnen: true,
			},
			{
				tagE: "15",
				eOrtE: "Licherode",
				schichtE: "N",
				abWE: "19:25",
				ab1E: "20:30",
				anEE: "21:05",
				beginE: "19:45",
				endeE: "06:15",
				abEE: "04:55",
				an1E: "05:30",
				anWE: "06:35",
				berechnen: true,
			},
			{
				tagE: "16",
				eOrtE: "Ersrode",
				schichtE: "N",
				abWE: "19:25",
				ab1E: "20:30",
				anEE: "20:55",
				beginE: "19:45",
				endeE: "06:15",
				abEE: "05:05",
				an1E: "05:30",
				anWE: "06:35",
				berechnen: true,
			},
			{
				tagE: "17",
				eOrtE: "Mühlbach",
				schichtE: "N",
				abWE: "19:25",
				ab1E: "20:30",
				anEE: "20:50",
				beginE: "19:45",
				endeE: "06:15",
				abEE: "05:10",
				an1E: "05:30",
				anWE: "06:35",
				berechnen: true,
			},
			{
				tagE: "18",
				eOrtE: "Kirchheim",
				schichtE: "N",
				abWE: "19:25",
				ab1E: "20:30",
				anEE: "20:40",
				beginE: "19:45",
				endeE: "06:15",
				abEE: "05:20",
				an1E: "05:30",
				anWE: "06:35",
				berechnen: true,
			},
			{
				tagE: "22",
				eOrtE: "Hattenbach",
				schichtE: "BN",
				abWE: "19:10",
				ab1E: "20:30",
				anEE: "20:45",
				beginE: "19:30",
				endeE: "06:15",
				abEE: "05:15",
				an1E: "05:30",
				anWE: "06:35",
				berechnen: true,
			},
			{
				tagE: "23",
				eOrtE: "Richthof",
				schichtE: "BN",
				abWE: "19:10",
				ab1E: "20:30",
				anEE: "20:50",
				beginE: "19:30",
				endeE: "06:15",
				abEE: "05:10",
				an1E: "05:30",
				anWE: "06:35",
				berechnen: true,
			},
			{
				tagE: "24",
				eOrtE: "Langenschwarz",
				schichtE: "BN",
				abWE: "19:10",
				ab1E: "20:30",
				anEE: "21:05",
				beginE: "19:30",
				endeE: "06:15",
				abEE: "04:55",
				an1E: "05:30",
				anWE: "06:35",
				berechnen: true,
			},
			{
				tagE: "25",
				eOrtE: "Michelsrombach",
				schichtE: "BN",
				abWE: "19:10",
				ab1E: "20:30",
				anEE: "21:10",
				beginE: "19:30",
				endeE: "06:15",
				abEE: "04:50",
				an1E: "05:30",
				anWE: "06:35",
				berechnen: true,
			},
		];

		// Führen Sie die berechnen-Funktion aus
		const result = berechnen(vorgabenU, daten, jahr, monat);

		// Überprüfen Sie die Ergebnisse
		expect(result).to.deep.equal(expected);
	});
});
